### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by djmtype** [lukethacoder/wp-webhook-netlify-deploy#9]
Either this documentation is outdated or unclear on how to obtain a Netlify API key. 

This does not exist: 
> Visit Netlify > OAuth Applications > Personal Access Tokens

**Comment by lukethacoder** [comment]
Thanks for the pick up @djmtype 

Looks like Netlify have moved where you obtain OAuth keys from.

they are now found under User Settings > Applications > OAuth

**Comment by djmtype** [comment]
@lukethacoder Please add this URL to your instructions so it's more obvious where to register the API: https://app.netlify.com/user/applications 

Otherwise, I'm afraid others including myself might try to set up OAuth using a Git service found here: 
app.netlify.com/sites/**my_netlify_site_name**/settings/access#oauth

Regardless, the webhook is working, but it's not building the site files from WP to my Github repo. 

```
9:56:30 AM: Build ready to start
9:56:35 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
9:56:35 AM: build-image tag: v3.3.2
9:56:35 AM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
9:56:35 AM: Fetching cached dependencies
9:56:35 AM: Starting to download cache of 3.7KB
9:56:35 AM: Finished downloading cache in 95.617482ms
9:56:35 AM: Starting to extract cache
9:56:35 AM: Finished extracting cache in 8.967605ms
9:56:35 AM: Finished fetching cache in 105.120812ms
9:56:35 AM: Starting to prepare the repo for build
9:56:35 AM: Preparing Git Reference refs/heads/master
9:56:36 AM: No build command found, continuing to publishing
9:56:36 AM: Starting to deploy site from '/'
9:56:36 AM: Creating deploy tree 
9:56:36 AM: 0 new files to upload
9:56:36 AM: 0 new functions to upload
9:56:36 AM: Starting post processing
9:56:36 AM: Post processing done
9:56:36 AM: Site is live
```

**Comment by lukethacoder** [comment]
@djmtype you shouldn't be looking for oAuth. Its a Personal Access Token you are generating.

Would you mind expanding on what you are trying to achieve with the building from WP to Github? 

The webhook is sent to Netlify, not Github. So your Github isn't part of this plugin. It is only pulled in by Netlify when the build is started. If you are wanting to push files from WordPress back into your Git repo, then you will need to find another solution.

**Comment by djmtype** [comment]
Hi @lukethacoder, please let me clarify some of my responses. 

Your initial documentation wasn't clear where/how to create a Netlify API. I'm not completely new to Netlify, but I'm still an amateur, so it wasn't apparent to me. If you include the same link I provided above (https://app.netlify.com/user/applications), it won't be confusing to anyone else from the very start.

I totally understand the webhook is sent to Netlify. That's why I posted my log above – to show it was working.  

Prior to using this plugin, I'd use SimplyStatic and have it export the files to a Github repo that Netlify was watching. As soon as I committed those files, Netlify would then rebuild the site. As you can see it's a pretty manual operation. I was looking for something more automated. 

So, I'd still need to use SimplyStatic with this plugin?

**Comment by lukethacoder** [comment]
@djmtype looks like you might need to go back to [SimplyStatic](https://www.simplystatic.co/). From the quick read of their docs there plugin wont work nicely with this plugin - at least now how you are thinking it might/should.

This plugin is built with a headless WordPress setup in mind. Sourcing your data in WordPress, and keeping the Front End separate in something like [GatsbyJS](https://www.gatsbyjs.org/) or [Now](https://zeit.co/now). Screenshot from the [GatsbyJS](https://www.gatsbyjs.org/) site shows nicely how it all links together.

![image](https://user-images.githubusercontent.com/13529535/62626453-cbe58780-b96a-11e9-90e6-f63469f716f0.png)

For what you are trying to achieve, this plugin won't be able to help. After a quick Google, may I suggest using the [WP2Static](https://wp2static.com/) plugin instead of SimplyStatic. It allows for auto deploying to Github, which then paired up with Netlify's built in auto deploy from Github functionality, you could easily and more autonomously update your site. 

If that doesn't excite you, the other way you go tackle this is to build your own plugin to achieve exactly what you want it to do. That was the initial inspiration for this plugin, I wanted functionality that wasn't there, so built it myself.

**Comment by djmtype** [comment]
Oh, this plugin should be used with a WP as a headless CMS. Well, that makes sense now. You could probably add Gridsome to the list, too. Luke, thanks alot for your time.

**Comment by mklueh** [comment]
I also thought it´s something like https://wp2static.com/ but with Netlify deploy and was wondering why I´m getting 404 on my Netlify site.

Maybe you can mention in the plugin description that it aims for headless and doesn´t deploy your Wordpress just for clarification :)
